In [5]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [5]:
ar=np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [8]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
 np.asarray(l)

array([1, 2, 3, 4])

In [11]:
a=[2,3,4]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b=np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
a=np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c=a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c[0]

1

In [22]:
c[0]=100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [28]:
#swallow copy

In [29]:
d=np.copy(a)

In [31]:
d

array([100,   2,   3,   4])

In [30]:
a

array([100,   2,   3,   4])

In [32]:
a[1]=400

In [33]:
a

array([100, 400,   3,   4])

In [34]:
d

array([100,   2,   3,   4])

In [35]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
iterable=(i*i for i in range(5))

In [39]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [41]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [42]:
#Numpy - Data Types

In [43]:
l=[2,3,4,5,6]

In [44]:
ar=np.array(l)

In [45]:
ar

array([2, 3, 4, 5, 6])

In [46]:
ar.ndim

1

In [47]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [48]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [49]:
ar2.ndim

2

In [50]:
ar.size

5

In [51]:
ar2.size

8

In [52]:
ar.shape

(5,)

In [53]:
ar2.shape

(2, 4)

In [54]:
ar.dtype

dtype('int64')

In [55]:
ar2.dtype

dtype('int64')

In [56]:
ar22=np.array([(1.4,45,54),(23,45,66)])

In [57]:
ar22

array([[ 1.4, 45. , 54. ],
       [23. , 45. , 66. ]])

In [58]:
ar22.dtype

dtype('float64')

In [59]:
list(range(5))

[0, 1, 2, 3, 4]

In [60]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [62]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [63]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [64]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
ar4=np.zeros((3,4,2,3))

In [71]:
ar4.ndim

4

In [70]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [72]:
np.ones(4)

array([1., 1., 1., 1.])

In [73]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
on=np.ones((2,3,2))

In [77]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [78]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [80]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [81]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [83]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [84]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [86]:
arr=np.random.randn(3,4)

In [87]:
import pandas as pd

In [88]:
pd.DataFrame(arr)

0         1         2         3
0  0.646460 -0.430119  0.240851 -0.140636
1  1.030934 -0.562223 -2.001494 -0.534890
2 -0.330927 -0.575043 -0.076686  0.753071

In [89]:
np.random.rand(3,4)

array([[0.65153553, 0.46618529, 0.88921757, 0.40165386],
       [0.91353963, 0.45295821, 0.34654659, 0.83049357],
       [0.4519796 , 0.64522909, 0.25609241, 0.26359789]])

In [90]:
np.random.randint(1,110,(3,4))

array([[ 85,  10,  31,  72],
       [109,  22,  37,  13],
       [ 70,   7,  90,  55]])

In [92]:
mkdir resources/02-26/

In [94]:
cd resources/02-26/

/home/jovyan/work/resources/02-26


In [95]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [96]:
arr=np.random.rand(3,4)

In [97]:
arr

array([[0.72261461, 0.45045712, 0.82644534, 0.98663642],
       [0.8274534 , 0.93962603, 0.6239897 , 0.77509984],
       [0.6072519 , 0.37829932, 0.80107347, 0.80442588]])

In [98]:
arr.reshape(6,2)

array([[0.72261461, 0.45045712],
       [0.82644534, 0.98663642],
       [0.8274534 , 0.93962603],
       [0.6239897 , 0.77509984],
       [0.6072519 , 0.37829932],
       [0.80107347, 0.80442588]])

In [99]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [100]:
arr.reshape(6,-1)

array([[0.72261461, 0.45045712],
       [0.82644534, 0.98663642],
       [0.8274534 , 0.93962603],
       [0.6239897 , 0.77509984],
       [0.6072519 , 0.37829932],
       [0.80107347, 0.80442588]])

In [102]:
arr1=arr.reshape(6,-134564846)

In [103]:
arr1

array([[0.72261461, 0.45045712],
       [0.82644534, 0.98663642],
       [0.8274534 , 0.93962603],
       [0.6239897 , 0.77509984],
       [0.6072519 , 0.37829932],
       [0.80107347, 0.80442588]])

In [104]:
arr1[1][1]

0.9866364203479686

In [107]:
arr1[2:5,1]

array([0.93962603, 0.77509984, 0.37829932])

In [109]:
arr=np.random.randint(1,100,(5,5))

In [110]:
arr

array([[77, 53, 37, 43, 80],
       [11, 33, 43, 95, 91],
       [49,  4, 44, 28, 85],
       [38, 90, 95, 59,  4],
       [87, 44, 83, 30, 40]])

In [111]:
arr>50

array([[ True,  True, False, False,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False,  True,  True,  True, False],
       [ True, False,  True, False, False]])

In [112]:
arr[arr>50]

array([77, 53, 80, 95, 91, 85, 90, 95, 59, 87, 83])

In [113]:
arr

array([[77, 53, 37, 43, 80],
       [11, 33, 43, 95, 91],
       [49,  4, 44, 28, 85],
       [38, 90, 95, 59,  4],
       [87, 44, 83, 30, 40]])

In [114]:
arr[2:4,[1,2]]

array([[ 4, 44],
       [90, 95]])

In [115]:
arr[0][0]=5000

In [116]:
arr

array([[5000,   53,   37,   43,   80],
       [  11,   33,   43,   95,   91],
       [  49,    4,   44,   28,   85],
       [  38,   90,   95,   59,    4],
       [  87,   44,   83,   30,   40]])

In [118]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [119]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [120]:
arr2

array([[1, 2, 2],
       [1, 2, 1],
       [1, 2, 2]])

In [121]:
arr1+arr2

array([[2, 4, 3],
       [2, 4, 2],
       [3, 3, 4]])

In [122]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 1, -1,  0]])

In [123]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 1. ],
       [2. , 0.5, 1. ]])

In [124]:
arr1*arr2

array([[1, 4, 2],
       [1, 4, 1],
       [2, 2, 4]])

In [125]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [126]:
arr2

array([[1, 2, 2],
       [1, 2, 1],
       [1, 2, 2]])

In [128]:
#for matrix multiplication
arr1@arr2

array([[ 4,  8,  6],
       [ 4,  8,  6],
       [ 5, 10,  9]])

In [129]:
arr1/0

/tmp/ipykernel_70/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [130]:
arr1+100

array([[101, 102, 101],
       [101, 102, 101],
       [102, 101, 102]])

In [132]:
arr1**2

array([[1, 4, 1],
       [1, 4, 1],
       [4, 1, 4]])

In [133]:
#Numpy - Broadcasting

In [6]:
arr=np.zeros((4,4))

In [7]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
row=np.array([1,2,3,4])

In [9]:
row

array([1, 2, 3, 4])

In [10]:
row.shape

(4,)

In [11]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [12]:
row.T

array([1, 2, 3, 4])

In [13]:
col=np.array([[1,2,3,4]])

In [14]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [15]:
col

array([[1, 2, 3, 4]])

In [16]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr1=np.random.randint(1,4,(3,4))

In [20]:
arr1

array([[3, 3, 2, 2],
       [1, 1, 1, 1],
       [3, 1, 2, 1]])

In [22]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        , 1.        ],
       [1.73205081, 1.        , 1.41421356, 1.        ]])

In [23]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [20.08553692,  2.71828183,  7.3890561 ,  2.71828183]])

In [24]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.30103   ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.47712125, 0.        , 0.30103   , 0.        ]])

**********************************************************vid2

In [1]:
#Numpy - Array Manupulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[8, 3, 5, 4],
       [9, 5, 5, 5],
       [2, 2, 9, 1]])

In [5]:
arr.reshape(6,2)

array([[8, 3],
       [5, 4],
       [9, 5],
       [5, 5],
       [2, 2],
       [9, 1]])

In [6]:
arr.reshape(2,6)

array([[8, 3, 5, 4, 9, 5],
       [5, 5, 2, 2, 9, 1]])

In [7]:
arr.reshape(2,-14654)

array([[8, 3, 5, 4, 9, 5],
       [5, 5, 2, 2, 9, 1]])

In [8]:
arr.T

array([[8, 9, 2],
       [3, 5, 2],
       [5, 5, 9],
       [4, 5, 1]])

In [9]:
arr.flatten()

array([8, 3, 5, 4, 9, 5, 5, 5, 2, 2, 9, 1])

In [10]:
arr1 = np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[8, 3, 5, 4],
       [9, 5, 5, 5],
       [2, 2, 9, 1]])

In [16]:
np.squeeze(arr)

array([[8, 3, 5, 4],
       [9, 5, 5, 5],
       [2, 2, 9, 1]])

In [17]:
data = np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 3, 4])

In [22]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [24]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 3, 4])

In [26]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [27]:
# Numpy - Binary Operations

In [28]:
arr1 = np.random.randint(1,10,(3,4))

In [29]:
arr2 = np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[8, 8, 9, 3],
       [6, 9, 7, 6],
       [3, 3, 8, 3]])

In [31]:
arr2

array([[6, 1, 8, 4],
       [5, 6, 7, 1],
       [3, 7, 4, 8]])

In [32]:
arr1+arr2

array([[14,  9, 17,  7],
       [11, 15, 14,  7],
       [ 6, 10, 12, 11]])

In [33]:
arr1*arr2

array([[48,  8, 72, 12],
       [30, 54, 49,  6],
       [ 9, 21, 32, 24]])

In [34]:
arr1/arr2

array([[1.33333333, 8.        , 1.125     , 0.75      ],
       [1.2       , 1.5       , 1.        , 6.        ],
       [1.        , 0.42857143, 2.        , 0.375     ]])

In [35]:
arr1-arr2

array([[ 2,  7,  1, -1],
       [ 1,  3,  0,  5],
       [ 0, -4,  4, -5]])

In [36]:
arr1%arr2

array([[2, 0, 1, 3],
       [1, 3, 0, 0],
       [0, 3, 0, 3]])

In [37]:
arr1**arr2

array([[  262144,        8, 43046721,       81],
       [    7776,   531441,   823543,        6],
       [      27,     2187,     4096,     6561]])

In [38]:
arr1&arr2

array([[0, 0, 8, 0],
       [4, 0, 7, 0],
       [3, 3, 0, 0]])

In [39]:
arr1

array([[8, 8, 9, 3],
       [6, 9, 7, 6],
       [3, 3, 8, 3]])

In [40]:
arr2

array([[6, 1, 8, 4],
       [5, 6, 7, 1],
       [3, 7, 4, 8]])

In [41]:
~arr1

array([[ -9,  -9, -10,  -4],
       [ -7, -10,  -8,  -7],
       [ -4,  -4,  -9,  -4]])

In [42]:
arr|arr2

array([[14,  3, 13,  4],
       [13,  7,  7,  5],
       [ 3,  7, 13,  9]])

In [43]:
arr1>arr2

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False,  True, False]])

In [44]:
#Numpy - String Functions

In [45]:
arr = np.array(['sudh', 'Kumar'])

In [46]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [47]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [48]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [49]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [50]:
#Numpy - Mathematical Functions

In [51]:
arr1

array([[8, 8, 9, 3],
       [6, 9, 7, 6],
       [3, 3, 8, 3]])

In [52]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825,  0.41211849,  0.14112001],
       [-0.2794155 ,  0.41211849,  0.6569866 , -0.2794155 ],
       [ 0.14112001,  0.14112001,  0.98935825,  0.14112001]])

In [53]:
np.cos(arr1)

array([[-0.14550003, -0.14550003, -0.91113026, -0.9899925 ],
       [ 0.96017029, -0.91113026,  0.75390225,  0.96017029],
       [-0.9899925 , -0.9899925 , -0.14550003, -0.9899925 ]])

In [54]:
np.tan(arr1)

array([[-6.79971146, -6.79971146, -0.45231566, -0.14254654],
       [-0.29100619, -0.45231566,  0.87144798, -0.29100619],
       [-0.14254654, -0.14254654, -6.79971146, -0.14254654]])

In [55]:
np.tanh(arr1)

array([[0.99999977, 0.99999977, 0.99999997, 0.99505475],
       [0.99998771, 0.99999997, 0.99999834, 0.99998771],
       [0.99505475, 0.99505475, 0.99999977, 0.99505475]])

In [56]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.95424251, 0.47712125],
       [0.77815125, 0.95424251, 0.84509804, 0.77815125],
       [0.47712125, 0.47712125, 0.90308999, 0.47712125]])

In [57]:
np.exp(arr1)

array([[2980.95798704, 2980.95798704, 8103.08392758,   20.08553692],
       [ 403.42879349, 8103.08392758, 1096.63315843,  403.42879349],
       [  20.08553692,   20.08553692, 2980.95798704,   20.08553692]])

In [58]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 3.        , 1.73205081],
       [2.44948974, 3.        , 2.64575131, 2.44948974],
       [1.73205081, 1.73205081, 2.82842712, 1.73205081]])

In [59]:
np.power(arr1, 2)

array([[64, 64, 81,  9],
       [36, 81, 49, 36],
       [ 9,  9, 64,  9]])

In [60]:
np.mean(arr1)

6.083333333333333

In [61]:
np.median(arr1)

6.5

In [62]:
np.std(arr1)

2.3614378858841256

In [63]:
np.var(arr1)

5.576388888888889

In [64]:
np.min(arr1)

3

In [65]:
np.max(arr1)

9

*****************************************************************vid3

In [66]:
#Sort, Search and Counting Functions

In [67]:
import numpy as np

In [68]:
arr= np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [69]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [70]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [72]:
np.searchsorted(arr,34)

12

In [73]:
arr1= np.array([0,345,454,0,0,0,0,0])

In [74]:
np.count_nonzero(arr1)

2

In [75]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [76]:
np.where(arr>6)

(array([5, 8]),)

In [77]:
np.extract(arr>6, arr)

array([ 72, 455])

In [78]:
np.extract(arr>3, arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [79]:
#Numpy - Byte Swapping

In [80]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [81]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [ ]:
#Numpy - Copies & Views

In [82]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [84]:
#Deep Copy
a=np.copy(arr)

In [85]:
#Swallow Copy
b=arr.view()

In [86]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [87]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [88]:
b[0]=67

In [89]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [90]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [91]:
#Numpy - Matrix Library

In [92]:
import numpy.matlib as nm

In [93]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [94]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
#Numpy - Linear Algebra

In [97]:
arr1=np.random.randint([[2,3],[4,5]])

In [98]:
arr2=np.random.randint([[5,3],[2,5]])

In [99]:
np.dot(arr1,arr2)

array([[0, 0],
       [4, 4]])

In [100]:
arr1@arr2

array([[0, 0],
       [4, 4]])